export const Config = {
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  PITCH_LENGTH: 60,
  PITCH_WIDTH: 33,
  KEEPER_ZONE_X: 19,
  HOOP_RADIUS: 0.86,
  HOOP_THICKNESS: 0.1,
  PLAYER_RADIUS: 1.6,
  VOLLEYBALL_RADIUS: 0.1,
  DODGEBALL_RADIUS: 0.1,
  // PLAYER_MAX_SPEED: 3,
  // PLAYER_MIN_DIR: 0.2,
};